name: stackdriver_iot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: richard <richard@bluetrainsoftware.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0
dependencies:
  googleapis: 0.54.0
  args: 1.5.2
  googleapis_auth: 0.2.11
  logging: ^0.11.3+2
  shelf: 0.7.5
  iot_api:
    path: api

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
